-- InWork core schema
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text,
  city text,
  age_group text,
  contact text,
  experience text,
  skills text[] default '{}',
  english boolean default false,
  work_preferences text[] default '{}',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.jobs (
  id bigint generated by default as identity primary key,
  title text not null,
  company text not null,
  place text,
  mode text,
  income text,
  currency text,
  tags text[] default '{}',
  description text,
  external_url text,
  international boolean default false,
  active boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.favorites (
  user_id uuid references auth.users(id) on delete cascade,
  job_id bigint references public.jobs(id) on delete cascade,
  created_at timestamptz default now(),
  primary key (user_id, job_id)
);

alter table public.profiles enable row level security;
alter table public.jobs enable row level security;
alter table public.favorites enable row level security;

create policy "profiles own row" on public.profiles for all using (auth.uid() = id) with check (auth.uid() = id);
create policy "jobs are public" on public.jobs for select using (active = true);
create policy "favorites own rows" on public.favorites for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, name) values (new.id, coalesce(new.raw_user_meta_data->>'full_name', new.email));
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
